<?PHP
	
	# POSTED VALUES FROM SCRIPT
	$FUNCTION = $_POST['FUNCTION'];
	$CLASS = $_POST['CLASS'];
	$ARGS = $_POST['ARGS'];
	
	# CLASS INSTANCE
	REQUIRE_ONCE $CLASS.'.php';
	$CLASS_INSTANCE = new $CLASS();
	
	# RUN CLASS METHOD WITH PASSED ARGS
	$CLASS_RETURN = $CLASS_INSTANCE	->	Run( $FUNCTION, $ARGS );
	
	# RETURN JSON TO SCRIPT
	ECHO JSON_ENCODE ( $CLASS_RETURN );
?>